### ISSUE TITLE
[bug] The scrollbar is not displayed after customization

### ISSUE THREAD

**Issue by gchumillas** [RobPethick/react-custom-scrollbars-2#10]
The following example uses the `renderTrackHorizontal` attribute, as described in [this document](https://github.com/malte-wessel/react-custom-scrollbars/blob/master/docs/customization.md), to customize the horizontal scrollbar:

https://codepen.io/gchumillas/pen/ExWLoOV

But the scrollbar is not displayed. It seems that the `style` attribute passed to the `renderTrackHorizontal` function doesn't contain information about the position.

**Comment by RobPethick** [comment]
There's an error in the documentation - apologies. To do this you'll also need to add the sizings


        right: 2,
        bottom: 2,
        left: 2,
        borderRadius: 3
        
are the defaults

**Comment by RobPethick** [comment]
Another example is here https://github.com/RobPethick/react-custom-scrollbars-2/blob/master/docs/customization.md

**Comment by gchumillas** [comment]
Thanks, it worked.
