### ISSUE TITLE
Microsoft Surface devices and touchscreen scrolling?

### ISSUE THREAD

**Issue by Xairoo** [RobPethick/react-custom-scrollbars-2#19]
Hope that's not an issue.

Month ago I had a Microsoft Surface (6 or 7) and I ran into some strange scrolling issues with custom scrollbars in combination with touch scrolling. Also noticed that problem on other sites if they used a custom scrollbar solution (https://roundme.com - https://roundme.com/tour/288112/view/903787/, https://web.icq.com - inside the chat). No matter if Chrome of Firefox. Scrolling wasn't possible with the touchscreen. You had to use the touchpad or a mouse. Happened only on the Surface. iOS and Android phones/tablets just worked.

Can a Surface owner confirm that touch (screen, not touchpad) scrolling is working with react-custom-scrollbars-2?

**Comment by mikegoatly** [comment]
@Xairoo I've just tried the site I work on that uses react-custom-scrollbars-2. I don't have any problems using the touchscreen to scroll with either a Surface Pro 7 or Surface Book. Tested with Edge and Chrome.

**Comment by Xairoo** [comment]
@mikegoatly thank you for that feedback!
