### ISSUE TITLE
ReferenceError react is not defined ? 

### ISSUE THREAD

**Issue by PokerJava** [RobPethick/react-custom-scrollbars-2#23]
use react-custom-scrollbars-2 
ReferenceError react is not defined

**Comment by RobPethick** [comment]
Assumedly you just need to add 

import React from 'react'; to the top of your page.

Doesn't sound like an issue with this lib

**Comment by TeckTn** [comment]
Hi,
I had this issue too when I migrate my create-react-app to vite.
I have this issue only in prod build.
I think that the library should not rely on some "auto-import" stuff to build correctly.
import React from 'react'; in this library makes sense for me.

**Comment by julianlionti** [comment]
HI! I have the same problem, React 17, vite and in production mode it says
React is not defined.
I don't know how to solve it

**Comment by danieljaguiar** [comment]
Same here... any news on how to solve this problem?
