### ISSUE TITLE
Scrollbar looks ugly on blur

### ISSUE THREAD

**Issue by jared3000** [RobPethick/react-custom-scrollbars-2#37]
https://user-images.githubusercontent.com/97551133/196073900-c1ea5677-d2d1-4839-a865-f4f89264a71a.mov

If you blur the scrolled element before the scrollbar fades away, you see the old ugly scroll bar flash in for a moment. This happens on my site and the demo as well. (MacOS/Chrome)

**Comment by jared3000** [comment]
just realized it's the hover stlying

**Comment by jared3000** [comment]
I realized this was a flash of the hover state, but I don't see how I can change that styling in the documentation. Is there an example of how to do that?

**Comment by wunmi-adb** [comment]
@jared3000 how did you fix it?

**Comment by jared3000** [comment]
> @jared3000 how did you fix it?

I ended up using a different plugin: https://www.npmjs.com/package/react-indiana-drag-scroll
However, that plugin isn't a 1-for-1 replacement so it might not work for what you're trying to do.
