### ISSUE TITLE
[Enhancement] Custom scrollbars are not visible on touch devices

### ISSUE THREAD

**Issue by robbeman** [RobPethick/react-custom-scrollbars-2#45]
Because this check relies on a scrollbar-width to be truthy this and scrollbars on mobile devices are usually floating/auto-hide and don't take up layout space.

https://github.com/RobPethick/react-custom-scrollbars-2/blob/a5838518889667dfc755d4d4d5b2e99018416c5c/src/Scrollbars/index.js#LL450C13-L450C30

Is this intentional? (Because this also affects mac-books with trackpad for example.)

One workaround is to force visible scrollbars (not confirmed to work on all devices) like so: https://stackoverflow.com/a/22907848/1629723

A prop/option to change this behaviour would be nice.

**Comment by Malberee** [comment]
I think this will help you. It's a little buggy, but overall it works.
https://www.npmjs.com/package/react-custom-scrollbars-with-mobile

**Comment by robbeman** [comment]
Hi, thanks for the reply, I kinda forgot about this. In the end I created some simple custom scrollbars using `framer-motion`.
