### ISSUE TITLE
Custom scrollbars not scrolling on position fixed elements

### ISSUE THREAD

**Issue by Dlyx24** [RobPethick/react-custom-scrollbars-2#9]
Hello, 
I have been using the react-custom-scrollbars-2 component for a while and I noticed that if you have a "position: fixed" style on an element the custom scrollbar wont scroll at all if your cursor happens to be on top of this element.

At first I though it was something about the Library sticky component I was using but I tried to replicate the issue with a custom div like this

```
<div style={{ position: "fixed", top: "150px", left: "500px", backgroundColor: "red" }}>
  test div
</div>
```

and the scrollbar didnt move if I had my cursor on top of this div element and tried to scroll.

I'm I doing something wrong?

**Comment by lwolczynski** [comment]
@Dlyx24 I'd like to help, but I can't recreate the issue. Can you paste more code or create a sandbox to show it?

**Comment by Dlyx24** [comment]
> @Dlyx24 I'd like to help, but I can't recreate the issue. Can you paste more code or create a sandbox to show it?

Sure! 

Fairly simple to test it just create a new react app with Typescript template using 
```
npx create-react-app my-app --template typescript

# or

yarn create react-app my-app --template typescript
```

Add the react custom scroll bars 2 dependency
(npm install react-custom-scrollbars-2   or   yarn add react-custom-scrollbars-2)

And just subtitute the App.tsx file with this code:

```
import "./App.css";
import { Scrollbars } from "react-custom-scrollbars-2";

function App() {
  return (
    <Scrollbars style={{ width: 500, height: 300 }} autoHide>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <div
        style={{
          position: "fixed",
          top: "150px",
          left: "300px",
          padding: "2px 5px",
          backgroundColor: "orange",
        }}
      >
        test div
      </div>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
      <p>Some great content...</p>
    </Scrollbars>
  );
}

export default App;
```

This will create a small window with the custom scrollbars working fine and a small orange rectangle with a fixed position. 
Put your cursor on top of that rectangle and try to scroll and you will see that It doesn't scroll at all, but if you move your cursor out of the rectangle it scrolls normally.

Any clue of why this is happening ?

**Comment by lwolczynski** [comment]
I have checked it and it looks not related to the library. If you swap a regular div for the Scrollbars component, the behavior is exactly the same. It's the way browser interprets the fixed element being independent from its parent.

I created a codesandbox [here](https://codesandbox.io/s/dreamy-mendel-8co6b), so you can test it out.

You have to figure out the way to overcome this. The quick fix would be adding `z-index: -1` to the fixed div style (uncomment line 31 if you play with the codesandbox). This may be not applicable in all cases, depends on content.

The proper solution for you could be adding a scroll event listener to the fixed div and propagating it to its parent.

**Comment by Dlyx24** [comment]
Thanks for your reply! It indeed works if you put ```z-index: -1```. However, as in my case I have some components inside that I have hover effects or I want the user to be able to select the text to copy it, this solution will make the whole component unselectable.

I found out that if you use ```pointer-events: none``` on the ```position: fixed``` component it has the same behaviour, and you can then adjust the styles to the parts where you want to have selection or hover effects with css. 

for instance if you have a link inside your fixed component you just overide the ```pointer-events: none``` to ```pointer-events: auto``` for that particular link.
This ofcourse means that the problem still applies if your cursor is right on top of the link and you try to scroll, but the margin for error is way reduced.

Once again thats for the help and the codesandbox example.

It is not a Custom scrollbars error. I am closing this issue.
